/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_NativeTest */

#ifndef _Included_org_NativeTest
#define _Included_org_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_NativeTest
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_NativeTest_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
